### ISSUE TITLE
Extra-wide margin for code blocks

### ISSUE THREAD

**Issue by jaakkocsc** [csc-training/slide-template#1]
With pandoc 2.7.3 all the code blocks will get an extra 1em margin around them. Thus, with three single line code blocks almost all of the slide's usable space has been wasted for empty space and there's no room left for anything else.

It appears that the html document produced by convert.py has some extra style definitions in the head section and the extra margin is defined there:
[…]div.sourceCode { margin: 1em 0; }[…]

**Comment by mlouhivu** [comment]
Thanks! The extra CSS inserted by pandoc into the head is problematic, especially since it changes between versions. We would be so much better off without it completely.
