### ISSUE TITLE
turning repository into template repository?

### ISSUE THREAD

**Issue by samumantha** [csc-training/slide-template#4]
Could this repository be turned into a template repository? -> https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-template-repository 

Main benefit: this template can be used to create a slide repository also on csc-training, which would benefit collaborative slide deck creation and sharing.
https://docs.github.com/en/enterprise-server@2.22/repositories/creating-and-managing-repositories/creating-a-repository-from-a-template

@mlouhivu ?

**Comment by samumantha** [comment]
I think this resolved itself just now, I misunderstood the whole machinery and thought all content here is needed in the repo to create slidedeck. So closing this issue

**Comment by mlouhivu** [comment]
Having a pure template repo is an idea worth exploring, though. Ideally, one would have one repo with everything needed to convert the slides and another that integrates nicely with the first one, while avoiding code/file duplication between them. Would require at least some restructuring and changes to the way the assets are used.
