### ISSUE TITLE
adding some general CSC slides to template?

### ISSUE THREAD

**Issue by samumantha** [csc-training/slide-template#5]
Do people usually have some general CSC/services slides in their slidedecks?
Could those be part of the template? Ie some subdirectory?

This would probably require a maintainer so that they always have the latest info/numbers, but whoever makes a presentation and checks the numbers anyway so could at that point also be updated in presentation (this is maybe too optimistic thought, but maybe still possible?).

Benefit: not everyone would have to create them themselves, but one could choose from pool of what is there already.

**Comment by mlouhivu** [comment]
Since the aim is to just offer an easy way to convert MD files into slides that use a specific style (CSC, ...) and it is getting used in all kinds of courses and talks, I think this should be implemented as a separate repo. Would be great to have such up-to-date material available, though.
